stages:
  - reactbuild
  - mavenbuild
  - deploybackend
  - deployfrontend

react-build:
    stage: reactbuild
    tags:
        - front_tag
    script:
        - cd front-end
        - npm install
    only:
        changes:
        - front-end/*

maven-build:
  stage: mavenbuild
  tags:
    - back_tag
  script:
    - cd back-end
    - mvn package -B
  only:
    changes:
    - back-end/*
      
deployBackend:
  stage: deploybackend
  tags:
   - back_tag
  script:
    - cd back-end
    - mvn package
    - sudo mv target/*.jar /srv/back-end.jar
    - sudo systemctl stop back-end
    - sudo systemctl start back-end
  only:
    refs:
    - main

deployFrontend:
  stage: deployfrontend
  tags:
   - front_tag
  script:
    - cd front-end
    - npm install
    - npm run build
    - sudo mv build /srv/front-end/
    - sudo systemctl stop front-end
    - sudo systemctl start front-end
  only:
    refs:
    - main